[package]
authors = ["Open Whisper Systems"]
name    = "kbupd_api"
version = "0.1.0"
license = "AGPL-3.0-or-later"
edition = "2018"

[dependencies]
kbupd_util   = { path = "../kbupd_util" }
serde        = "1.0"
serde_derive = "1.0"
