server:
  listenHostPort:                                 # host:port to listen on for TLS connections
  targetHostPort:                                 # host:port to proxy connections to
  caCertificatePem:                               # PEM-encoded CA certificate to authenticate clients against

client:
  clientCertificatePkcs12:                        # (optional) base64-encoded DER PKCS12 client certificate and key
  caCertificates:                                 # Root CA certificates to trust when validating server certificate
    - system                                      # Trust all certificates in /etc/ssl/certs/
    - customPem:                                  # PEM-encoded CA certificate to trust
  hostnameValidation:                             # Options for validating server certificate hostname
    acceptInvalid                                 # Do not validate the server certificate hostname
    hostname:                                     # Hostname to require in the server certificate
