name: service
description: run a Makefile target in the service directory
inputs:
  target:
    description: Makefile targets to run
runs:
  using: docker
  image: '../../../service/docker/Dockerfile'
  entrypoint: /bin/bash
  args:
    - "-c"
    - "mkdir -p /github/workspace/service/build && cp -a /github/workspace/service /home/rust/src && rm -r /home/rust/src/build && ln -s /github/workspace/service/build /home/rust/src/build && HOME=/home/rust && make -C /home/rust/src/ ${{ inputs.target }}"
